const workDetails = {
    work1: {
        title: "Dashen Bank Head Quarters CEO Office",
        description: "The CEO's office at Dashen Bank's headquarters epitomizes executive refinement and functionality. Combining sleek modernity with timeless elegance, the space features high-quality materials such as rich woods and luxurious fabrics, exuding prestige and sophistication. The layout is thoughtfully designed to optimize workflow and productivity, with an executive desk positioned strategically to command attention and facilitate decision-making. Bespoke furnishings and curated artwork add a personal touch, reflecting the CEO's leadership style and vision while creating an inviting and inspiring environment for strategic planning and meetings.",
        images: [   
            "images/works/1.DASHEN CEO/00.webp", 
            "images/works/1.DASHEN CEO/01.webp", 
            "images/works/1.DASHEN CEO/02.webp", 
            "images/works/1.DASHEN CEO/03.webp", 
            "images/works/1.DASHEN CEO/04.webp", 
            "images/works/1.DASHEN CEO/05.webp", 
            "images/works/1.DASHEN CEO/06.webp", 
            "images/works/1.DASHEN CEO/07.webp", 
            "images/works/1.DASHEN CEO/08.webp", 
            "images/works/1.DASHEN CEO/09.webp", 
            "images/works/1.DASHEN CEO/10.webp", 
            "images/works/1.DASHEN CEO/11.webp", 
            "images/works/1.DASHEN CEO/12.webp", 
    
        ]
    },
    work2: {
        title: "Dashen bank HQ conference hall interior design",
        description: "Dashen Bank's headquarters conference hall epitomizes modern sophistication and functionality. Featuring sleek lines, premium materials, and contemporary furnishings, the space sets the stage for impactful meetings and events. State-of-the-art audiovisual technology seamlessly integrates into the design, offering dynamic presentation capabilities, while flexible seating arrangements ensure versatility for various corporate gatherings.",
        images: [   
            "images/works/2.DASHEN CONFERENCE HALL/00.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/01.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/02.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/03.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/04.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/05.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/06.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/07.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/08.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/09.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/10.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/11.webp", 
            "images/works/2.DASHEN CONFERENCE HALL/12.webp", 
        ]
    },
    work3: {
        title: "Dashen Bank Head Quarters Lobby and Gallery",
        description: "In the Dashen Bank lobby, sophistication greets practicality, housing both a reception and a comfortable waiting area. Bathed in natural light and adorned with contemporary accents, this space seamlessly integrates efficiency with elegance. Meanwhile, the gallery serves as a captivating showcase of the bank's rich history and prestigious awards. Visitors are invited to journey through time, surrounded by curated displays that honor the institution's legacy and achievements. Welcome to a lobby where tradition meets innovation, and every corner tells a story of excellence.",
        images: [
            "images/works/3.DASHEN GALLERY/00.webp", 
            "images/works/3.DASHEN GALLERY/01.webp", 
            "images/works/3.DASHEN GALLERY/02.webp", 
            "images/works/3.DASHEN GALLERY/03.webp", 
            "images/works/3.DASHEN GALLERY/04.webp", 
            "images/works/3.DASHEN GALLERY/05.webp", 
            "images/works/3.DASHEN GALLERY/06.webp", 
            "images/works/3.DASHEN GALLERY/07.webp", 
            "images/works/3.DASHEN GALLERY/08.webp", 
            "images/works/3.DASHEN GALLERY/09.webp", 
            "images/works/3.DASHEN GALLERY/10.webp", 
            "images/works/3.DASHEN GALLERY/11.webp", 
        ]
    },
    work4: {
        title: "Dashen Bank District Offices",
        description: "Dashen Bank's primary objective was to establish representative spaces that mirror the company's image and culture within an innovative environment. To achieve this, we conceived a design concept centered on simplicity and minimalism. By embracing clean lines, uncluttered spaces, and contemporary aesthetics, we crafted a workplace that effectively reflects the essence of the company while promoting a modern and innovative atmosphere.",
        images: [   
            "images/works/4.DASHEN DISTRICT/00.webp", 
            "images/works/4.DASHEN DISTRICT/01.webp", 
            "images/works/4.DASHEN DISTRICT/02.webp", 
            "images/works/4.DASHEN DISTRICT/03.webp", 
            "images/works/4.DASHEN DISTRICT/04.webp", 
            "images/works/4.DASHEN DISTRICT/05.webp", 
            "images/works/4.DASHEN DISTRICT/06.webp", 
            "images/works/4.DASHEN DISTRICT/07.webp", 
        ]
    },
    work5: {
        title: "Dashen Bank Branch Standardization",
        description: "Vi Designs PLC secured the bid for the renovation and branch standardization project for Dashen Bank. Our design approach focused on utilizing modular elements to ensure flexibility across various conditions and spaces, while also enhancing the bank's operational efficiency and reflecting its identity. By incorporating adaptable components, we aimed to optimize the working process within the bank while maintaining a consistent and representative aesthetic throughout its branches.",
        images: [
            "images/works/5.DASHEN BRANCH/00.webp", 
            "images/works/5.DASHEN BRANCH/01.webp", 
            "images/works/5.DASHEN BRANCH/02.webp", 
            "images/works/5.DASHEN BRANCH/03.webp", 
            "images/works/5.DASHEN BRANCH/04.webp", 
            "images/works/5.DASHEN BRANCH/05.webp",
            "images/works/5.DASHEN BRANCH/06.webp", 
            "images/works/5.DASHEN BRANCH/07.webp", 
            "images/works/5.DASHEN BRANCH/08.webp", 
            "images/works/5.DASHEN BRANCH/09.webp", 
        ]
    },
    work6: {
        title: "Global bank Ethiopia Interior Design",
        description: "Step into the dynamic world of Global Bank Ethiopia's interior design, where tradition meets innovation across offices, branches, and digital banking spaces. In our offices, contemporary open layouts foster collaboration and creativity, while sleek furnishings and strategic lighting enhance productivity. Branches exude accessibility and warmth, with inviting customer service areas complemented by cutting-edge digital banking facilities. Seamless integration of technology ensures a frictionless experience for customers engaging with our digital banking services, embodying our commitment to modernity and customer-centric design.",
        images: [   
            "images/works/6.GLOBAL BANK/00.webp", 
            "images/works/6.GLOBAL BANK/01.webp", 
            "images/works/6.GLOBAL BANK/02.webp", 
            "images/works/6.GLOBAL BANK/03.webp", 
            "images/works/6.GLOBAL BANK/04.webp", 
            "images/works/6.GLOBAL BANK/05.webp", 
            "images/works/6.GLOBAL BANK/06.webp", 
            "images/works/6.GLOBAL BANK/07.webp", 
            "images/works/6.GLOBAL BANK/08.webp", 
            "images/works/6.GLOBAL BANK/09.webp", 
            "images/works/6.GLOBAL BANK/10.webp",
        ]
    },
    work7: {
        title: "Ato Mehari Baryagabr Residence Interior Design",
        description: "The interior design for the G+4 Residence epitomizes modern luxury, meticulously curated to meet the client's request. From grand common areas to intimate private spaces, every detail reflects careful consideration. The selection of materials, furniture, and spatial elements ensures a cohesive and refined living experience, embodying sophistication and elegance throughout the residence.",
        images: [
            "images/works/7.MEHARI RESIDENCE/00.webp", 
            "images/works/7.MEHARI RESIDENCE/01.webp", 
            "images/works/7.MEHARI RESIDENCE/02.webp", 
            "images/works/7.MEHARI RESIDENCE/03.webp", 
            "images/works/7.MEHARI RESIDENCE/04.webp", 
            "images/works/7.MEHARI RESIDENCE/05.webp", 
            "images/works/7.MEHARI RESIDENCE/06.webp", 
            "images/works/7.MEHARI RESIDENCE/07.webp", 
            "images/works/7.MEHARI RESIDENCE/08.webp", 
            "images/works/7.MEHARI RESIDENCE/09.webp", 
            "images/works/7.MEHARI RESIDENCE/10.webp", 
            "images/works/7.MEHARI RESIDENCE/11.webp", 
            "images/works/7.MEHARI RESIDENCE/12.webp", 
            "images/works/7.MEHARI RESIDENCE/13.webp", 
            "images/works/7.MEHARI RESIDENCE/14.webp", 
            "images/works/7.MEHARI RESIDENCE/15.webp", 
            "images/works/7.MEHARI RESIDENCE/16.webp", 
            "images/works/7.MEHARI RESIDENCE/17.webp", 
            "images/works/7.MEHARI RESIDENCE/18.webp", 
        ]
    },
    work8: {
        title: "Ato Mehari Baryagabr Architectural Design",
        description: "Nestled on an 800sq.m plot in Mekelle, Ethiopia, our mixed-use building project redefines urban living. Featuring shopping and office spaces on the lower floors and a luxurious hotel above, including rooms, spa, pool, and restaurant, it epitomizes modern functionality and innovation. With shared amenities, sustainability features, and a commitment to vibrant urban culture, it offers an unparalleled experience in contemporary living.",
        images: [  
            "images/works/8.MEHARI HOTEL/00.webp", 
            "images/works/8.MEHARI HOTEL/01.webp", 
            "images/works/8.MEHARI HOTEL/02.webp", 
            "images/works/8.MEHARI HOTEL/03.webp", 
            "images/works/8.MEHARI HOTEL/04.webp", 
        ]
    },
    work9: {
        title: "Dejen Import & Export Workplace Interior Design",
        description: "For Dejen & Import Export Company, our office interior design and supervision focus on merging sophistication with functionality. We optimize space usage, ensuring efficient workflow and flexibility for future growth. The design reflects Dejen's brand identity through modern aesthetics and ergonomic workstations, fostering a professional yet inviting atmosphere for employees and visitors alike.",
        images: [
            "images/works/9.DEJEN IMPORT/00.webp", 
            "images/works/9.DEJEN IMPORT/01.webp", 
            "images/works/9.DEJEN IMPORT/02.webp", 
            "images/works/9.DEJEN IMPORT/03.webp", 
        ]
    },
    work10: {
        title: "MAISHUM RESORT INTERIOR DESIGN",
        description: "This was an Interior Design and Visualization Project done for a resort to be built in Axum. The design utilized the tradition construction materials and images of the area.",
        images: [  
            "images/works/10.MAISHUM/00.webp", 
            "images/works/10.MAISHUM/01.webp", 
            "images/works/10.MAISHUM/02.webp",
        ]
    },
    work11: {
        title: "South Star International Hotel Landscape Design",
        description: "South Star, a prestigious five-star hotel in Hawassa, Ethiopia, entrusted our office with the landscape design for its second phase project, spanning 3000 square meters. In an era where urban hotels prioritize space efficiency, we aimed to create a unique outdoor environment for relaxation and recreation. Leveraging Hawassa's lakeside allure, our design incorporates water features around main sitting areas, providing tranquility. These serene spaces are complemented by flexible green areas, enhancing the ambiance and offering versatility for guests to enjoy the hotel grounds.",
        images: [
            "images/works/11.SOUTH STAR LANDSCAPE/00.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/01.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/02.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/03.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/04.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/05.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/06.webp", 
            "images/works/11.SOUTH STAR LANDSCAPE/07.webp", 
        ]
    },
    work12: {
        title: "CCD Real Estate Residence Full Landscape Design",
        description: "This project entails a comprehensive landscape design for the residence of Ato Yared Feyissa, situated within the compound of CCD Real Estate in the vibrant area of Legetafo, Ethiopia. Our goal was to craft a serene living environment where the family can relish daily moments together, while also incorporating specific features to reflect the client's passions. Spanning 1000 square meters, the compound's front yard design showcases a harmonious blend of elements, including a refreshing swimming pool, a stylish pergola, an inviting outdoor jacuzzi, and lush garden spaces. Each component is meticulously integrated to create a tranquil oasis that perfectly complements the family's lifestyle and preferences.",
        images: [  
            "images/works/12.YARED RESIDENCE LANDSCAPE/00.webp", 
            "images/works/12.YARED RESIDENCE LANDSCAPE/01.webp", 
            "images/works/12.YARED RESIDENCE LANDSCAPE/02.webp", 
            "images/works/12.YARED RESIDENCE LANDSCAPE/03.webp",
        ]
    },
    work13: {
        title: "Ethswitch Head Quarter",
        description: "VI Designs successfully carried out the interior design and construction supervision of the EthSwitch Headquarters, delivering a modern and functional workplace that reflects the company’s identity and values. The project scope included the design and execution of the main reception area, chief and directors’ offices, staff workspaces, and all supporting facilities, ensuring a cohesive aesthetic, efficient space planning, and high-quality finishes. Careful attention was given to both functionality and visual impact, creating a professional environment that enhances productivity and leaves a lasting impression on visitors.",
        images: [
            "images/works/13.ETHSWITCH/00.webp",
            "images/works/13.ETHSWITCH/1.webp",
            "images/works/13.ETHSWITCH/2.webp",
            "images/works/13.ETHSWITCH/3.webp",
            "images/works/13.ETHSWITCH/4.webp",
            "images/works/13.ETHSWITCH/5.webp", 
            "images/works/13.ETHSWITCH/6.webp",
            "images/works/13.ETHSWITCH/7.webp",
            "images/works/13.ETHSWITCH/8.webp",
            "images/works/13.ETHSWITCH/9.webp",
            "images/works/13.ETHSWITCH/10.webp",
            "images/works/13.ETHSWITCH/11.webp",
            "images/works/13.ETHSWITCH/12.webp",
            "images/works/13.ETHSWITCH/13.webp",
            "images/works/13.ETHSWITCH/14.webp",
            "images/works/13.ETHSWITCH/15.webp"
        ]
    },
    work14: {
        title: "Dashen Bank Innovation Hub",
        description: "VI Designs undertook the interior design and supervision of the Dashen Bank Innovation Hub, creating a dynamic and inspiring workspace that supports creativity and collaboration. The project encompassed the reception area, meeting rooms, offices, and a dedicated relaxation area, all carefully designed to balance functionality with comfort. Emphasis was placed on modern finishes, flexible layouts, and a welcoming atmosphere that fosters innovation while promoting a relaxing and productive working environment for staff and visitors alike. The project is now complete and successfully in use.",
        images: [
            "images/works/14.DASHEN BANK INNOVATION HUB/00.webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (2).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (3).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (4).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (5).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (6).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (7).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (8).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (9).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (10).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (11).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (12).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (13).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (14).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (15).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (16).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (17).webp",
            "images/works/14.DASHEN BANK INNOVATION HUB/1 (18).webp",
        ]
    },
    work15: {
        title: "ABAY HOMES REAL ESTATE OFFICE INTERIOR DESIGN",
        description: "Vi Designs PLC delivered a comprehensive interior- and exterior-3D-visualisation package for Abay Homes’ mixed-use residential development near the Mexico area in Addis Ababa. The assignment encompassed full architectural renderings of exterior façades and landscaped settings, alongside detailed interior design and photorealistic 3-D renderings of all typologies — one-bedroom, two-bedroom and three-bedroom units — each carefully crafted for light, materiality and human scale. In addition, shared amenity zones were depicted in the design suite, including a café breakout space, a sports/fitness area and a swimming-pool deck. To support marketing outreach and immersive client engagement, a fully interactive walk-through website was implemented. ",
        link: "https://www.keypano.com/v/2uf6n5zcjb5183-1749160084.html",        
        images: [
            "images/works/15.ABAY HOMES REAL ESTATE/00.webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(1).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(2).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(3).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(4).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(5).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(6).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(7).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(8).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(9).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(10).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(11).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(12).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(13).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(14).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(15).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(16).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(17).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(18).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(19).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(20).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(21).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(22).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(23).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(24).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(25).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(26).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(27).webp",
            "images/works/15.ABAY HOMES REAL ESTATE/_(28).webp",
        ]
    },
};

export { workDetails };