"""Share byte-identical image files; keep removed copies in WEBTEMP.

Run directly to consolidate duplicates: python script/image_assets.py
The small alias module also lets JavaScript resolve generated image paths.
"""
from pathlib import Path
import hashlib
import json
import shutil

ROOT = Path(__file__).resolve().parent.parent
ALIASES = ROOT / 'script/image-aliases.js'


def read_aliases():
    if not ALIASES.exists():
        return {}
    return json.loads(ALIASES.read_text(encoding='utf-8').split('export const imageAliases = ', 1)[1].strip().removesuffix(';'))


def resolve_image(path):
    aliases = read_aliases()
    return aliases.get(path, path)


def consolidate_duplicates():
    aliases = read_aliases()
    # Regenerated variants may now differ; only missing paths retain old aliases.
    aliases = {source: target for source, target in aliases.items() if not (ROOT / source).exists()}
    groups = {}
    for path in sorted((ROOT / 'images').rglob('*')):
        if path.is_file():
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            groups.setdefault(digest, []).append(path)

    archive = ROOT / 'WEBTEMP/archive'
    assert archive.resolve().is_relative_to(ROOT) and not archive.is_symlink()
    manifest_path = archive / 'manifest.json'
    manifest = json.loads(manifest_path.read_text(encoding='utf-8')) if manifest_path.exists() else []
    moved = saved = 0
    for digest, paths in groups.items():
        if len(paths) < 2:
            continue
        # Prefer original paths, then medium display copies when two sizes match.
        paths.sort(key=lambda path: (0 if path.relative_to(ROOT).as_posix().startswith('images/gallery/large/') else 1, path.as_posix()))
        keeper = paths[0].relative_to(ROOT).as_posix()
        for source in paths[1:]:
            relative = source.relative_to(ROOT).as_posix()
            destination = archive / 'duplicate-images' / relative
            # Check final absolute targets before moving or removing any file.
            assert source.resolve().is_relative_to(ROOT / 'images') and not source.is_symlink()
            assert destination.resolve().is_relative_to(archive.resolve())
            size = source.stat().st_size
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                assert hashlib.sha256(destination.read_bytes()).hexdigest() == digest
                source.unlink()  # The identical backup already exists.
            else:
                shutil.move(str(source), str(destination))
                manifest.append({'original': relative, 'archive': destination.relative_to(ROOT).as_posix(), 'bytes': size, 'reason': 'byte-identical duplicate', 'kept': keeper, 'sha256': digest})
            aliases[relative] = keeper
            moved += 1
            saved += size

    # Flatten aliases so the browser needs only one lookup.
    for source, target in aliases.items():
        seen = {source}
        while target in aliases:
            assert target not in seen, 'Circular image alias'
            seen.add(target)
            target = aliases[target]
        aliases[source] = target
        assert (ROOT / target).is_file(), target
    ALIASES.write_text('// Generated by image_assets.py. Identical images share one file.\nexport const imageAliases = ' + json.dumps(aliases, indent=2) + ';\n', encoding='utf-8')
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    print(f'Moved {moved} duplicate files into WEBTEMP/archive/duplicate-images ({saved / 1_000_000:.2f} MB).')


if __name__ == '__main__':
    consolidate_duplicates()
