// Generated by optimize_images.py; do not edit by hand.
export const imageWidths = {
  "images/gallery/large/10.MAISHUM/00.webp": [
    768,
    1240
  ],
  "images/gallery/large/10.MAISHUM/01.webp": [
    768,
    1154
  ],
  "images/gallery/large/10.MAISHUM/02.webp": [
    768,
    1423
  ],
  "images/gallery/large/11.SOUTH STAR LANDSCAPE/00.webp": [
    768,
    1369
  ],
  "images/gallery/large/11.SOUTH STAR LANDSCAPE/02.webp": [
    768,
    1412
  ],
  "images/gallery/large/13.ETHSWITCH/00.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/1.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/10.webp": [
    768,
    838
  ],
  "images/gallery/large/13.ETHSWITCH/11.webp": [
    768,
    837
  ],
  "images/gallery/large/13.ETHSWITCH/12.webp": [
    768,
    841
  ],
  "images/gallery/large/13.ETHSWITCH/13.webp": [
    768,
    838
  ],
  "images/gallery/large/13.ETHSWITCH/14.webp": [
    768,
    839
  ],
  "images/gallery/large/13.ETHSWITCH/15.webp": [
    768,
    836
  ],
  "images/gallery/large/13.ETHSWITCH/2.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/3.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/4.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/5.webp": [
    768,
    834
  ],
  "images/gallery/large/13.ETHSWITCH/6.webp": [
    768,
    836
  ],
  "images/gallery/large/13.ETHSWITCH/7.webp": [
    768,
    838
  ],
  "images/gallery/large/13.ETHSWITCH/8.webp": [
    768,
    839
  ],
  "images/gallery/large/13.ETHSWITCH/9.webp": [
    768,
    837
  ],
  "images/gallery/large/3.DASHEN GALLERY/00.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/01.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/02.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/03.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/04.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/05.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/06.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/07.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/08.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/09.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/10.webp": [
    768,
    1200
  ],
  "images/gallery/large/3.DASHEN GALLERY/11.webp": [
    768,
    1200
  ],
  "images/gallery/large/6.GLOBAL BANK/00.webp": [
    768,
    1203
  ],
  "images/gallery/large/6.GLOBAL BANK/01.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/02.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/03.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/04.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/05.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/06.webp": [
    768,
    1175
  ],
  "images/gallery/large/6.GLOBAL BANK/07.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/08.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/09.webp": [
    768,
    1280
  ],
  "images/gallery/large/6.GLOBAL BANK/10.webp": [
    768,
    1280
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/01.webp": [
    644,
    644
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/02.webp": [
    768,
    900
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/03.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/04.webp": [
    768,
    957
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/05.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/07.webp": [
    768,
    957
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/08.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/09.webp": [
    768,
    956
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/10.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/11.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/12.webp": [
    768,
    959
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/13.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/14.webp": [
    768,
    958
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/15.webp": [
    768,
    957
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/16.webp": [
    768,
    959
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/17.webp": [
    768,
    959
  ],
  "images/gallery/large/7.MEHARI RESIDENCE/18.webp": [
    768,
    958
  ],
  "images/gallery/large/8.MEHARI HOTEL/00.webp": [
    490,
    490
  ],
  "images/gallery/large/8.MEHARI HOTEL/01.webp": [
    768,
    920
  ],
  "images/gallery/large/8.MEHARI HOTEL/02.webp": [
    768,
    1280
  ],
  "images/gallery/large/8.MEHARI HOTEL/04.webp": [
    768,
    920
  ]
};
