"""Generate smaller display images without changing the full-screen originals.

Install Pillow once: python -m pip install -r script/requirements.txt
Run after adding or changing photographs: python script/optimize_images.py
"""

from pathlib import Path
import re
import json

from PIL import Image, ImageOps
from image_assets import resolve_image, consolidate_duplicates

ROOT = Path(__file__).resolve().parent.parent
VARIANTS = {"thumbnail": 192, "small": 768, "medium": 1440}


def gallery_sources():
    """Read the explicit image paths in the editable project catalog."""
    data = (ROOT / "script/data.js").read_text(encoding="utf-8")
    return sorted(set(re.findall(r'[\"\'](images/gallery/large/[^\"\']+\.webp)[\"\']', data)))


def variant_path(source, size):
    return source.replace("images/gallery/large/", f"images/gallery/{size}/", 1)


def save_smaller(source, destination, width, quality=82):
    """Keep the original composition and aspect ratio; never upscale."""
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original).convert("RGB")
        target_width = min(width, image.width)
        target_size = (target_width, round(target_width * image.height / image.width))
        if destination.exists() and destination.stat().st_mtime >= source.stat().st_mtime:
            with Image.open(destination) as existing:
                if existing.size == target_size:
                    return
        image = image.resize(target_size, Image.Resampling.LANCZOS)
        destination.parent.mkdir(parents=True, exist_ok=True)
        image.save(destination, "WEBP", quality=quality, method=6)


def main():
    count = 0
    widths = {}
    for source in gallery_sources():
        for size, width in VARIANTS.items():
            save_smaller(ROOT / resolve_image(source), ROOT / variant_path(source, size), width)
            count += 1
        with Image.open(ROOT / resolve_image(source)) as original:
            if original.width < VARIANTS['medium']:
                widths[source] = [min(original.width, VARIANTS['small']), original.width]
    # Actual widths keep srcset correct for originals smaller than our targets.
    manifest = '// Generated by optimize_images.py; do not edit by hand.\n'
    manifest += 'export const imageWidths = ' + json.dumps(widths, indent=2) + ';\n'
    (ROOT / 'script/image-sizes.js').write_text(manifest, encoding='utf-8')
    consolidate_duplicates()
    print(f"Ready: {count} gallery images. Full-screen originals are unchanged.")


if __name__ == "__main__":
    main()
